//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  builds: Builds;
  buildsConnection: BuildsConnection;
  cases: Cases;
  casesConnection: CasesConnection;
  threads: Threads;
  threadsConnection: ThreadsConnection;
  reviews: Reviews;
  reviewsConnection: ReviewsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBuildsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBuildsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BuildsFilter>;
};


export type QueryCasesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCasesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CasesFilter>;
};


export type QueryThreadsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryThreadsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ThreadsFilter>;
};


export type QueryReviewsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryReviewsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ReviewsFilter>;
};

export type DocumentFilter = {
  builds?: InputMaybe<BuildsFilter>;
  cases?: InputMaybe<CasesFilter>;
  threads?: InputMaybe<ThreadsFilter>;
  reviews?: InputMaybe<ReviewsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Builds | Cases | Threads | Reviews | Folder;

export type BuildsComponents = {
  __typename?: 'BuildsComponents';
  cpu?: Maybe<Scalars['String']['output']>;
  motherboard?: Maybe<Scalars['String']['output']>;
  ram?: Maybe<Scalars['String']['output']>;
  gpu?: Maybe<Scalars['String']['output']>;
  storage?: Maybe<Scalars['String']['output']>;
  psu?: Maybe<Scalars['String']['output']>;
  case?: Maybe<Scalars['String']['output']>;
  cooler?: Maybe<Scalars['String']['output']>;
};

export type Builds = Node & Document & {
  __typename?: 'Builds';
  title: Scalars['String']['output'];
  purpose: Scalars['String']['output'];
  purposeLabel: Scalars['String']['output'];
  date: Scalars['String']['output'];
  description: Scalars['String']['output'];
  components?: Maybe<BuildsComponents>;
  complexity?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  heroImage?: Maybe<Scalars['String']['output']>;
  gallery?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BuildsComponentsFilter = {
  cpu?: InputMaybe<StringFilter>;
  motherboard?: InputMaybe<StringFilter>;
  ram?: InputMaybe<StringFilter>;
  gpu?: InputMaybe<StringFilter>;
  storage?: InputMaybe<StringFilter>;
  psu?: InputMaybe<StringFilter>;
  case?: InputMaybe<StringFilter>;
  cooler?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BuildsFilter = {
  title?: InputMaybe<StringFilter>;
  purpose?: InputMaybe<StringFilter>;
  purposeLabel?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  description?: InputMaybe<StringFilter>;
  components?: InputMaybe<BuildsComponentsFilter>;
  complexity?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  gallery?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BuildsConnectionEdges = {
  __typename?: 'BuildsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Builds>;
};

export type BuildsConnection = Connection & {
  __typename?: 'BuildsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BuildsConnectionEdges>>>;
};

export type CasesKeySpecs = {
  __typename?: 'CasesKeySpecs';
  label?: Maybe<Scalars['String']['output']>;
  value?: Maybe<Scalars['String']['output']>;
};

export type Cases = Node & Document & {
  __typename?: 'Cases';
  title: Scalars['String']['output'];
  device: Scalars['String']['output'];
  category: Scalars['String']['output'];
  date: Scalars['String']['output'];
  problem?: Maybe<Scalars['String']['output']>;
  diagnosis?: Maybe<Scalars['String']['output']>;
  solution?: Maybe<Scalars['String']['output']>;
  result?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  heroImage?: Maybe<Scalars['String']['output']>;
  gallery?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  captions?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  keySpecs?: Maybe<Array<Maybe<CasesKeySpecs>>>;
  schemaType?: Maybe<Scalars['String']['output']>;
  summaryForSocial?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CasesKeySpecsFilter = {
  label?: InputMaybe<StringFilter>;
  value?: InputMaybe<StringFilter>;
};

export type CasesFilter = {
  title?: InputMaybe<StringFilter>;
  device?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  problem?: InputMaybe<StringFilter>;
  diagnosis?: InputMaybe<StringFilter>;
  solution?: InputMaybe<StringFilter>;
  result?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  gallery?: InputMaybe<ImageFilter>;
  captions?: InputMaybe<StringFilter>;
  keySpecs?: InputMaybe<CasesKeySpecsFilter>;
  schemaType?: InputMaybe<StringFilter>;
  summaryForSocial?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type CasesConnectionEdges = {
  __typename?: 'CasesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Cases>;
};

export type CasesConnection = Connection & {
  __typename?: 'CasesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CasesConnectionEdges>>>;
};

export type Threads = Node & Document & {
  __typename?: 'Threads';
  handle?: Maybe<Scalars['String']['output']>;
  date: Scalars['String']['output'];
  gallery?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  alts?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  url?: Maybe<Scalars['String']['output']>;
  video?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ThreadsFilter = {
  handle?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  gallery?: InputMaybe<ImageFilter>;
  alts?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  video?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ThreadsConnectionEdges = {
  __typename?: 'ThreadsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Threads>;
};

export type ThreadsConnection = Connection & {
  __typename?: 'ThreadsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ThreadsConnectionEdges>>>;
};

export type Reviews = Node & Document & {
  __typename?: 'Reviews';
  author: Scalars['String']['output'];
  source?: Maybe<Scalars['String']['output']>;
  rating?: Maybe<Scalars['Float']['output']>;
  date: Scalars['String']['output'];
  device?: Maybe<Scalars['String']['output']>;
  avatar?: Maybe<Scalars['String']['output']>;
  gallery?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  captions?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ReviewsFilter = {
  author?: InputMaybe<StringFilter>;
  source?: InputMaybe<StringFilter>;
  rating?: InputMaybe<NumberFilter>;
  date?: InputMaybe<DatetimeFilter>;
  device?: InputMaybe<StringFilter>;
  avatar?: InputMaybe<ImageFilter>;
  gallery?: InputMaybe<ImageFilter>;
  captions?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ReviewsConnectionEdges = {
  __typename?: 'ReviewsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Reviews>;
};

export type ReviewsConnection = Connection & {
  __typename?: 'ReviewsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ReviewsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateBuilds: Builds;
  createBuilds: Builds;
  updateCases: Cases;
  createCases: Cases;
  updateThreads: Threads;
  createThreads: Threads;
  updateReviews: Reviews;
  createReviews: Reviews;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateBuildsArgs = {
  relativePath: Scalars['String']['input'];
  params: BuildsMutation;
};


export type MutationCreateBuildsArgs = {
  relativePath: Scalars['String']['input'];
  params: BuildsMutation;
};


export type MutationUpdateCasesArgs = {
  relativePath: Scalars['String']['input'];
  params: CasesMutation;
};


export type MutationCreateCasesArgs = {
  relativePath: Scalars['String']['input'];
  params: CasesMutation;
};


export type MutationUpdateThreadsArgs = {
  relativePath: Scalars['String']['input'];
  params: ThreadsMutation;
};


export type MutationCreateThreadsArgs = {
  relativePath: Scalars['String']['input'];
  params: ThreadsMutation;
};


export type MutationUpdateReviewsArgs = {
  relativePath: Scalars['String']['input'];
  params: ReviewsMutation;
};


export type MutationCreateReviewsArgs = {
  relativePath: Scalars['String']['input'];
  params: ReviewsMutation;
};

export type DocumentUpdateMutation = {
  builds?: InputMaybe<BuildsMutation>;
  cases?: InputMaybe<CasesMutation>;
  threads?: InputMaybe<ThreadsMutation>;
  reviews?: InputMaybe<ReviewsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  builds?: InputMaybe<BuildsMutation>;
  cases?: InputMaybe<CasesMutation>;
  threads?: InputMaybe<ThreadsMutation>;
  reviews?: InputMaybe<ReviewsMutation>;
};

export type BuildsComponentsMutation = {
  cpu?: InputMaybe<Scalars['String']['input']>;
  motherboard?: InputMaybe<Scalars['String']['input']>;
  ram?: InputMaybe<Scalars['String']['input']>;
  gpu?: InputMaybe<Scalars['String']['input']>;
  storage?: InputMaybe<Scalars['String']['input']>;
  psu?: InputMaybe<Scalars['String']['input']>;
  case?: InputMaybe<Scalars['String']['input']>;
  cooler?: InputMaybe<Scalars['String']['input']>;
};

export type BuildsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  purpose?: InputMaybe<Scalars['String']['input']>;
  purposeLabel?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  components?: InputMaybe<BuildsComponentsMutation>;
  complexity?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  gallery?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type CasesKeySpecsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  value?: InputMaybe<Scalars['String']['input']>;
};

export type CasesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  device?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  problem?: InputMaybe<Scalars['String']['input']>;
  diagnosis?: InputMaybe<Scalars['String']['input']>;
  solution?: InputMaybe<Scalars['String']['input']>;
  result?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  gallery?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  captions?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  keySpecs?: InputMaybe<Array<InputMaybe<CasesKeySpecsMutation>>>;
  schemaType?: InputMaybe<Scalars['String']['input']>;
  summaryForSocial?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ThreadsMutation = {
  handle?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  gallery?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  alts?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  url?: InputMaybe<Scalars['String']['input']>;
  video?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ReviewsMutation = {
  author?: InputMaybe<Scalars['String']['input']>;
  source?: InputMaybe<Scalars['String']['input']>;
  rating?: InputMaybe<Scalars['Float']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  device?: InputMaybe<Scalars['String']['input']>;
  avatar?: InputMaybe<Scalars['String']['input']>;
  gallery?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  captions?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type DatetimeFilter = {
  after?: string | null | undefined;
  before?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type BuildsComponentsFilter = {
  cpu?: StringFilter | null | undefined;
  motherboard?: StringFilter | null | undefined;
  ram?: StringFilter | null | undefined;
  gpu?: StringFilter | null | undefined;
  storage?: StringFilter | null | undefined;
  psu?: StringFilter | null | undefined;
  case?: StringFilter | null | undefined;
  cooler?: StringFilter | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type RichTextFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
};

export type BuildsFilter = {
  title?: StringFilter | null | undefined;
  purpose?: StringFilter | null | undefined;
  purposeLabel?: StringFilter | null | undefined;
  date?: DatetimeFilter | null | undefined;
  description?: StringFilter | null | undefined;
  components?: BuildsComponentsFilter | null | undefined;
  complexity?: StringFilter | null | undefined;
  tags?: StringFilter | null | undefined;
  heroImage?: ImageFilter | null | undefined;
  gallery?: ImageFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type CasesKeySpecsFilter = {
  label?: StringFilter | null | undefined;
  value?: StringFilter | null | undefined;
};

export type CasesFilter = {
  title?: StringFilter | null | undefined;
  device?: StringFilter | null | undefined;
  category?: StringFilter | null | undefined;
  date?: DatetimeFilter | null | undefined;
  problem?: StringFilter | null | undefined;
  diagnosis?: StringFilter | null | undefined;
  solution?: StringFilter | null | undefined;
  result?: StringFilter | null | undefined;
  tags?: StringFilter | null | undefined;
  heroImage?: ImageFilter | null | undefined;
  gallery?: ImageFilter | null | undefined;
  captions?: StringFilter | null | undefined;
  keySpecs?: CasesKeySpecsFilter | null | undefined;
  schemaType?: StringFilter | null | undefined;
  summaryForSocial?: StringFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type ThreadsFilter = {
  handle?: StringFilter | null | undefined;
  date?: DatetimeFilter | null | undefined;
  gallery?: ImageFilter | null | undefined;
  alts?: StringFilter | null | undefined;
  url?: StringFilter | null | undefined;
  video?: StringFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type ReviewsFilter = {
  author?: StringFilter | null | undefined;
  source?: StringFilter | null | undefined;
  rating?: NumberFilter | null | undefined;
  date?: DatetimeFilter | null | undefined;
  device?: StringFilter | null | undefined;
  avatar?: ImageFilter | null | undefined;
  gallery?: ImageFilter | null | undefined;
  captions?: StringFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type BuildsPartsFragment = { __typename: 'Builds', title: string, purpose: string, purposeLabel: string, date: string, description: string, complexity: string | null, tags: Array<string | null> | null, heroImage: string | null, gallery: Array<string | null> | null, body: any, components: { __typename: 'BuildsComponents', cpu: string | null, motherboard: string | null, ram: string | null, gpu: string | null, storage: string | null, psu: string | null, case: string | null, cooler: string | null } | null };

export type CasesPartsFragment = { __typename: 'Cases', title: string, device: string, category: string, date: string, problem: string | null, diagnosis: string | null, solution: string | null, result: string | null, tags: Array<string | null> | null, heroImage: string | null, gallery: Array<string | null> | null, captions: Array<string | null> | null, schemaType: string | null, summaryForSocial: string | null, body: any, keySpecs: Array<{ __typename: 'CasesKeySpecs', label: string | null, value: string | null } | null> | null };

export type ThreadsPartsFragment = { __typename: 'Threads', handle: string | null, date: string, gallery: Array<string | null> | null, alts: Array<string | null> | null, url: string | null, video: string | null, body: any };

export type ReviewsPartsFragment = { __typename: 'Reviews', author: string, source: string | null, rating: number | null, date: string, device: string | null, avatar: string | null, gallery: Array<string | null> | null, captions: Array<string | null> | null, body: any };

export type BuildsQueryVariables = Exact<{
  relativePath: string;
}>;


export type BuildsQuery = { builds: { __typename: 'Builds', id: string, title: string, purpose: string, purposeLabel: string, date: string, description: string, complexity: string | null, tags: Array<string | null> | null, heroImage: string | null, gallery: Array<string | null> | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, components: { __typename: 'BuildsComponents', cpu: string | null, motherboard: string | null, ram: string | null, gpu: string | null, storage: string | null, psu: string | null, case: string | null, cooler: string | null } | null } };

export type BuildsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: BuildsFilter | null | undefined;
}>;


export type BuildsConnectionQuery = { buildsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Builds', id: string, title: string, purpose: string, purposeLabel: string, date: string, description: string, complexity: string | null, tags: Array<string | null> | null, heroImage: string | null, gallery: Array<string | null> | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, components: { __typename: 'BuildsComponents', cpu: string | null, motherboard: string | null, ram: string | null, gpu: string | null, storage: string | null, psu: string | null, case: string | null, cooler: string | null } | null } | null } | null> | null } };

export type CasesQueryVariables = Exact<{
  relativePath: string;
}>;


export type CasesQuery = { cases: { __typename: 'Cases', id: string, title: string, device: string, category: string, date: string, problem: string | null, diagnosis: string | null, solution: string | null, result: string | null, tags: Array<string | null> | null, heroImage: string | null, gallery: Array<string | null> | null, captions: Array<string | null> | null, schemaType: string | null, summaryForSocial: string | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, keySpecs: Array<{ __typename: 'CasesKeySpecs', label: string | null, value: string | null } | null> | null } };

export type CasesConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: CasesFilter | null | undefined;
}>;


export type CasesConnectionQuery = { casesConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Cases', id: string, title: string, device: string, category: string, date: string, problem: string | null, diagnosis: string | null, solution: string | null, result: string | null, tags: Array<string | null> | null, heroImage: string | null, gallery: Array<string | null> | null, captions: Array<string | null> | null, schemaType: string | null, summaryForSocial: string | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, keySpecs: Array<{ __typename: 'CasesKeySpecs', label: string | null, value: string | null } | null> | null } | null } | null> | null } };

export type ThreadsQueryVariables = Exact<{
  relativePath: string;
}>;


export type ThreadsQuery = { threads: { __typename: 'Threads', id: string, handle: string | null, date: string, gallery: Array<string | null> | null, alts: Array<string | null> | null, url: string | null, video: string | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ThreadsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: ThreadsFilter | null | undefined;
}>;


export type ThreadsConnectionQuery = { threadsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Threads', id: string, handle: string | null, date: string, gallery: Array<string | null> | null, alts: Array<string | null> | null, url: string | null, video: string | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ReviewsQueryVariables = Exact<{
  relativePath: string;
}>;


export type ReviewsQuery = { reviews: { __typename: 'Reviews', id: string, author: string, source: string | null, rating: number | null, date: string, device: string | null, avatar: string | null, gallery: Array<string | null> | null, captions: Array<string | null> | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ReviewsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: ReviewsFilter | null | undefined;
}>;


export type ReviewsConnectionQuery = { reviewsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Reviews', id: string, author: string, source: string | null, rating: number | null, date: string, device: string | null, avatar: string | null, gallery: Array<string | null> | null, captions: Array<string | null> | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const BuildsPartsFragmentDoc = gql`
    fragment BuildsParts on Builds {
  __typename
  title
  purpose
  purposeLabel
  date
  description
  components {
    __typename
    cpu
    motherboard
    ram
    gpu
    storage
    psu
    case
    cooler
  }
  complexity
  tags
  heroImage
  gallery
  body
}
    `;
export const CasesPartsFragmentDoc = gql`
    fragment CasesParts on Cases {
  __typename
  title
  device
  category
  date
  problem
  diagnosis
  solution
  result
  tags
  heroImage
  gallery
  captions
  keySpecs {
    __typename
    label
    value
  }
  schemaType
  summaryForSocial
  body
}
    `;
export const ThreadsPartsFragmentDoc = gql`
    fragment ThreadsParts on Threads {
  __typename
  handle
  date
  gallery
  alts
  url
  video
  body
}
    `;
export const ReviewsPartsFragmentDoc = gql`
    fragment ReviewsParts on Reviews {
  __typename
  author
  source
  rating
  date
  device
  avatar
  gallery
  captions
  body
}
    `;
export const BuildsDocument = gql`
    query builds($relativePath: String!) {
  builds(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BuildsParts
  }
}
    ${BuildsPartsFragmentDoc}`;
export const BuildsConnectionDocument = gql`
    query buildsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BuildsFilter) {
  buildsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BuildsParts
      }
    }
  }
}
    ${BuildsPartsFragmentDoc}`;
export const CasesDocument = gql`
    query cases($relativePath: String!) {
  cases(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CasesParts
  }
}
    ${CasesPartsFragmentDoc}`;
export const CasesConnectionDocument = gql`
    query casesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CasesFilter) {
  casesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CasesParts
      }
    }
  }
}
    ${CasesPartsFragmentDoc}`;
export const ThreadsDocument = gql`
    query threads($relativePath: String!) {
  threads(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ThreadsParts
  }
}
    ${ThreadsPartsFragmentDoc}`;
export const ThreadsConnectionDocument = gql`
    query threadsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ThreadsFilter) {
  threadsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ThreadsParts
      }
    }
  }
}
    ${ThreadsPartsFragmentDoc}`;
export const ReviewsDocument = gql`
    query reviews($relativePath: String!) {
  reviews(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ReviewsParts
  }
}
    ${ReviewsPartsFragmentDoc}`;
export const ReviewsConnectionDocument = gql`
    query reviewsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ReviewsFilter) {
  reviewsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ReviewsParts
      }
    }
  }
}
    ${ReviewsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      builds(variables: BuildsQueryVariables, options?: C): Promise<{data: BuildsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BuildsQueryVariables, query: string}> {
        return requester<{data: BuildsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BuildsQueryVariables, query: string}, BuildsQueryVariables>(BuildsDocument, variables, options);
      },
    buildsConnection(variables?: BuildsConnectionQueryVariables, options?: C): Promise<{data: BuildsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BuildsConnectionQueryVariables, query: string}> {
        return requester<{data: BuildsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BuildsConnectionQueryVariables, query: string}, BuildsConnectionQueryVariables>(BuildsConnectionDocument, variables, options);
      },
    cases(variables: CasesQueryVariables, options?: C): Promise<{data: CasesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CasesQueryVariables, query: string}> {
        return requester<{data: CasesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CasesQueryVariables, query: string}, CasesQueryVariables>(CasesDocument, variables, options);
      },
    casesConnection(variables?: CasesConnectionQueryVariables, options?: C): Promise<{data: CasesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CasesConnectionQueryVariables, query: string}> {
        return requester<{data: CasesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CasesConnectionQueryVariables, query: string}, CasesConnectionQueryVariables>(CasesConnectionDocument, variables, options);
      },
    threads(variables: ThreadsQueryVariables, options?: C): Promise<{data: ThreadsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ThreadsQueryVariables, query: string}> {
        return requester<{data: ThreadsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ThreadsQueryVariables, query: string}, ThreadsQueryVariables>(ThreadsDocument, variables, options);
      },
    threadsConnection(variables?: ThreadsConnectionQueryVariables, options?: C): Promise<{data: ThreadsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ThreadsConnectionQueryVariables, query: string}> {
        return requester<{data: ThreadsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ThreadsConnectionQueryVariables, query: string}, ThreadsConnectionQueryVariables>(ThreadsConnectionDocument, variables, options);
      },
    reviews(variables: ReviewsQueryVariables, options?: C): Promise<{data: ReviewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsQueryVariables, query: string}> {
        return requester<{data: ReviewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsQueryVariables, query: string}, ReviewsQueryVariables>(ReviewsDocument, variables, options);
      },
    reviewsConnection(variables?: ReviewsConnectionQueryVariables, options?: C): Promise<{data: ReviewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsConnectionQueryVariables, query: string}> {
        return requester<{data: ReviewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsConnectionQueryVariables, query: string}, ReviewsConnectionQueryVariables>(ReviewsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  